[package]
name = "shared_protocol"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
license.workspace = true
publish = false

[dependencies]
async-trait.workspace = true
chacha20poly1305.workspace = true
constriction.workspace = true
half.workspace = true
hkdf.workspace = true
ml-dsa.workspace = true
ml-kem.workspace = true
rand_core.workspace = true
serde.workspace = true
serde-big-array.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio.workspace = true
x25519-dalek.workspace = true

[dev-dependencies]
rand.workspace = true
