/* pulzZ C ABI — auto-generated by cbindgen. Do not edit. */

#ifndef PULZZ_H
#define PULZZ_H

/* Warning: this file is auto-generated by cbindgen. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include "stddef.h"
#include "stdint.h"

/**
 * Major.minor.patch packed as `major<<16 | minor<<8 | patch`.
 */
#define ABI_VERSION (((0 << 16) | (4 << 8)) | 0)

enum PulzzResult
#if __STDC_VERSION__ >= 202311L
  : uint32_t
#endif // __STDC_VERSION__ >= 202311L
 {
    Ok = 0,
    InvalidArg = 1,
    InvalidState = 2,
    ConnectionFailed = 3,
    HandshakeFailed = 4,
    CompressionFailed = 5,
    Timeout = 6,
    BufferTooSmall = 7,
    EndOfStream = 8,
    Internal = 99,
};
#if __STDC_VERSION__ >= 202311L
typedef enum PulzzResult PulzzResult;
#else
typedef uint32_t PulzzResult;
#endif // __STDC_VERSION__ >= 202311L

enum PulzzCarrierKind
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
    WebSocket = 0,
    Tcp = 1,
    QuicStream = 2,
    QuicDatagram = 3,
    WebTransport = 4,
    UdpDatagram = 5,
};
#if __STDC_VERSION__ >= 202311L
typedef enum PulzzCarrierKind PulzzCarrierKind;
#else
typedef uint8_t PulzzCarrierKind;
#endif // __STDC_VERSION__ >= 202311L

enum PulzzSecurityProfile
#if __STDC_VERSION__ >= 202311L
  : uint8_t
#endif // __STDC_VERSION__ >= 202311L
 {
    PqMutualV1 = 0,
    PqSimpleV1 = 1,
    ClassicRef1 = 2,
};
#if __STDC_VERSION__ >= 202311L
typedef enum PulzzSecurityProfile PulzzSecurityProfile;
#else
typedef uint8_t PulzzSecurityProfile;
#endif // __STDC_VERSION__ >= 202311L

typedef struct {
    PulzzCarrierKind carrier;
    PulzzSecurityProfile security;
    uint32_t batch_size;
    int32_t zstd_level;
    uint64_t timeout_ms;
} PulzzConfig;

typedef void *PulzzClientHandle;

/**
 * Read-only byte slice passed across the FFI boundary.
 */
typedef struct {
    const uint8_t *ptr;
    size_t len;
} PulzzSlice;

typedef void *PulzzBatchHandle;

typedef void *PulzzServerHandle;

typedef void *PulzzSessionHandle;

/**
 * ABI version (packed: major<<16 | minor<<8 | patch).
 *
 * Returns `0x0004_0000` for v0.4.0.
 */
 uint32_t pulzz_abi_version(void);

/**
 * Human-readable version string. Caller must NOT free; the returned
 * pointer is valid for the lifetime of the shared library.
 */
 const char *pulzz_version_string(void);

/**
 * Returns the last error message set on the current thread, or NULL if
 * no error is set. The returned pointer is valid until the next `pulzz_*`
 * call on the same thread.
 */
 const char *pulzz_last_error(void);

/**
 * Parse a raw wire-format Record from bytes. This is the wire-bytes
 * compatibility surface for cross-language tests (Go, C, Python).
 *
 * # Arguments
 * - `bytes_ptr`: pointer to the raw wire bytes
 * - `bytes_len`: length of the raw wire bytes
 * - `out_item_id`: output parameter for the record's item_id (u64)
 * - `out_payload_ptr`: output parameter; will be set to a pointer to the
 *   payload bytes (caller must NOT free; valid until the next pulzz_* call)
 * - `out_payload_len`: output parameter for the payload length
 * - `out_record_type`: output parameter for the record type (u8)
 *
 * # Returns
 * `PulzzResult::Ok` on success, `PulzzResult::WireError` on parse failure.
 *
 * # Safety
 * `bytes_ptr` must be valid for `bytes_len` bytes. The output pointers must
 * be valid for writing one u64, one *mut u8, one usize, one u8 respectively.
 */

PulzzResult pulzz_parse_record(const uint8_t *bytes_ptr,
                               size_t bytes_len,
                               uint64_t *out_item_id,
                               uint8_t **out_payload_ptr,
                               size_t *out_payload_len,
                               uint8_t *out_record_type);

/**
 * Create a new client from a config. The handle is owned by the caller and
 * must be freed via `pulzz_client_free`.
 *
 * Returns `PULZZ_OK` on success and writes the handle to `*out_client`.
 */
 PulzzResult pulzz_client_new(const PulzzConfig *config, PulzzClientHandle *out_client);

/**
 * Connect to a server at `url`. Blocks the calling thread on a tokio
 * runtime until the connection succeeds or fails.
 */
 PulzzResult pulzz_client_connect(PulzzClientHandle handle, const char *url);

/**
 * Send a single item.
 */
 PulzzResult pulzz_client_send(PulzzClientHandle handle, uint64_t item_id, PulzzSlice payload);

 PulzzResult pulzz_batch_new(PulzzBatchHandle *out_batch);


PulzzResult pulzz_batch_add(PulzzBatchHandle batch,
                            uint64_t item_id,
                            uint8_t source_kind,
                            PulzzSlice payload);

 void pulzz_batch_free(PulzzBatchHandle batch);

 PulzzResult pulzz_client_send_batch(PulzzClientHandle handle, PulzzBatchHandle batch);

/**
 * Receive the next record. On success writes the record's item_id to
 * `*out_item_id`, allocates a payload buffer and writes its pointer + len
 * to `*out_payload_ptr` + `*out_payload_len`. The caller MUST free the
 * payload buffer via `pulzz_record_free_payload`.
 *
 * Returns `PULZZ_OK` on success, `PULZZ_ERR_TIMEOUT` if no record arrived
 * within `timeout_ms`, `PULZZ_ERR_END_OF_STREAM` if the peer closed the
 * connection.
 */

PulzzResult pulzz_client_recv(PulzzClientHandle handle,
                              uint64_t *out_item_id,
                              uint8_t **out_payload_ptr,
                              size_t *out_payload_len,
                              uint8_t *out_record_type,
                              uint32_t timeout_ms);

/**
 * Free a payload buffer previously returned by `pulzz_client_recv`.
 */
 void pulzz_record_free_payload(uint8_t *ptr, size_t len);

 PulzzResult pulzz_client_close(PulzzClientHandle handle);

 void pulzz_client_free(PulzzClientHandle handle);

 PulzzResult pulzz_server_new(const PulzzConfig *config, PulzzServerHandle *out_server);

 PulzzResult pulzz_server_bind(PulzzServerHandle handle, const char *addr);


PulzzResult pulzz_server_accept(PulzzServerHandle handle,
                                PulzzSessionHandle *out_session,
                                uint32_t _timeout_ms);

 PulzzResult pulzz_session_send(PulzzSessionHandle handle, uint64_t item_id, PulzzSlice payload);


PulzzResult pulzz_session_recv(PulzzSessionHandle handle,
                               uint64_t *out_item_id,
                               uint8_t **out_payload_ptr,
                               size_t *out_payload_len,
                               uint8_t *out_record_type,
                               uint32_t _timeout_ms);

 PulzzResult pulzz_session_close(PulzzSessionHandle handle);

 void pulzz_session_free(PulzzSessionHandle handle);

 void pulzz_server_free(PulzzServerHandle handle);

#endif  /* PULZZ_H */
