[package]
name = "pulzz-python"
version.workspace = true
edition.workspace = true
description = "Python binding for pulzZ SDK via PyO3."
license.workspace = true
publish.workspace = true
repository.workspace = true

[dependencies]
pulzz-sdk = { path = "../../sdk" }
shared_protocol = { path = "../../shared_protocol" }
pyo3 = { version = "0.22", features = ["extension-module"] }
tokio = { workspace = true }

[lib]
name = "pulzz"
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"
