/* C ↔ Rust cross-language wire-bytes compatibility test (Wave 5 T-5.d).
 *
 * Verifies that C can parse the same wire bytes that Rust produces, using
 * the C ABI's pulzz_parse_record function.
 *
 * Build:
 *   cc ffi/tests/c_cross_language.c -I ffi/include \
 *     target/debug/libpulzz_ffi.a -lpthread -ldl -lm \
 *     -o target/debug/c_cross_language && ./target/debug/c_cross_language
 *
 * The hex bytes below were generated by:
 *   cargo run --bin gen_cross_lang_bytes -p pulzz-sdk
 */

#include <pulzz.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Record 1: ExactState, stream_id=1, item_id=42, payload="cross-lang-test" */
/* Generated by: cargo run --bin gen_cross_lang_bytes -p pulzz-sdk */
static const char *HEX_1 =
    "020100000000000000000000000000000000000000"
    "110300002a000000000000000f000000"
    "63726f73732d6c616e672d74657374"
    "00000000000000000000000000000000";
static const uint64_t EXPECTED_ITEM_ID_1 = 42;
static const char EXPECTED_PAYLOAD_1[] = "cross-lang-test";
static const uint8_t EXPECTED_RECORD_TYPE_1 = 17; /* ExactState */

/* Record 2: ExactState, stream_id=7, item_id=99, payload="hello" */
static const char *HEX_2 =
    "020700000000000000000000000100000000000000"
    "11030000630000000000000005000000"
    "68656c6c6f"
    "abababababababababababababababab";
static const uint64_t EXPECTED_ITEM_ID_2 = 99;
static const char EXPECTED_PAYLOAD_2[] = "hello";
static const uint8_t EXPECTED_RECORD_TYPE_2 = 17; /* ExactState */

static int hex_val(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    if (c >= 'a' && c <= 'f') return c - 'a' + 10;
    if (c >= 'A' && c <= 'F') return c - 'A' + 10;
    return -1;
}

static unsigned char *hex_to_bytes(const char *hex, size_t *out_len) {
    size_t hex_len = strlen(hex);
    size_t bytes_len = hex_len / 2;
    unsigned char *bytes = (unsigned char *)malloc(bytes_len);
    if (!bytes) return NULL;
    for (size_t i = 0; i < bytes_len; i++) {
        int hi = hex_val(hex[2 * i]);
        int lo = hex_val(hex[2 * i + 1]);
        if (hi < 0 || lo < 0) { free(bytes); return NULL; }
        bytes[i] = (unsigned char)((hi << 4) | lo);
    }
    *out_len = bytes_len;
    return bytes;
}

static int test_parse_record(const char *hex, uint64_t want_id,
                              const char *want_payload, uint8_t want_type,
                              const char *test_name) {
    size_t bytes_len = 0;
    unsigned char *bytes = hex_to_bytes(hex, &bytes_len);
    if (!bytes) {
        printf("FAIL %s: hex_to_bytes failed\n", test_name);
        return 1;
    }

    uint64_t item_id = 0;
    uint8_t *payload_ptr = NULL;
    size_t payload_len = 0;
    uint8_t record_type = 0;

    PulzzResult result = pulzz_parse_record(
        bytes, bytes_len, &item_id, &payload_ptr, &payload_len, &record_type);

    free(bytes);

    if (result != Ok) {
        printf("FAIL %s: pulzz_parse_record returned %d\n", test_name, (int)result);
        return 1;
    }
    if (item_id != want_id) {
        printf("FAIL %s: item_id=%llu, want %llu\n", test_name,
               (unsigned long long)item_id, (unsigned long long)want_id);
        return 1;
    }
    if (record_type != want_type) {
        printf("FAIL %s: record_type=%u, want %u\n", test_name,
               (unsigned)record_type, (unsigned)want_type);
        return 1;
    }
    size_t want_payload_len = strlen(want_payload);
    if (payload_len != want_payload_len) {
        printf("FAIL %s: payload_len=%zu, want %zu\n", test_name, payload_len, want_payload_len);
        return 1;
    }
    if (memcmp(payload_ptr, want_payload, payload_len) != 0) {
        printf("FAIL %s: payload mismatch\n", test_name);
        return 1;
    }
    printf("PASS %s: item_id=%llu, payload=%zu bytes, type=%u\n", test_name,
           (unsigned long long)item_id, payload_len, (unsigned)record_type);
    return 0;
}

static int test_version_and_constants(void) {
    uint32_t version = pulzz_abi_version();
    /* (0 << 16) | (6 << 8) | 0 = 0x00000600 */
    if (version != 0x00000600) {
        printf("FAIL test_version: abi_version=0x%08x, want 0x00000600\n", version);
        return 1;
    }
    const char *vstr = pulzz_version_string();
    if (strstr(vstr, "pulzZ") == NULL) {
        printf("FAIL test_version: version_string='%s' doesn't contain 'pulzZ'\n", vstr);
        return 1;
    }
    printf("PASS test_version: abi=0x%08x, str='%s'\n", version, vstr);
    return 0;
}

int main(void) {
    printf("C <-> Rust cross-language wire-bytes test\n");
    int failures = 0;
    failures += test_parse_record(HEX_1, EXPECTED_ITEM_ID_1,
                                  EXPECTED_PAYLOAD_1, EXPECTED_RECORD_TYPE_1,
                                  "test_parse_record_1");
    failures += test_parse_record(HEX_2, EXPECTED_ITEM_ID_2,
                                  EXPECTED_PAYLOAD_2, EXPECTED_RECORD_TYPE_2,
                                  "test_parse_record_2");
    failures += test_version_and_constants();
    if (failures == 0) {
        printf("\nAll C cross-language tests PASSED\n");
        return 0;
    }
    printf("\n%d C cross-language tests FAILED\n", failures);
    return 1;
}
