//! pulzZ C ABI.
//!
//! Public surface: every `extern "C"` function is panic-safe (wrapped in
//! `catch_unwind`), null-checks every pointer, and reports failures via the
//! `pulzz_result_t` enum + thread-local last-error string.
//!
//! The crate is a `cdylib` producing `libpulzz.so` / `pulzz.dll` / a
//! static `.a`. The C header `pulzz.h` is generated by `cbindgen`.

// Pre-existing clippy lints silenced at crate level (spec §0.2 bug #10):
// - not_unsafe_ptr_arg_deref: FFI functions accept raw pointers from C; the
//   caller (C side) is responsible for pointer validity. Marking every
//   extern "C" fn as unsafe would pollute the C API.
// - large_enum_variant: the pulzz_result_t enum and some FFI result structs
//   are intentionally large to match the C ABI contract.
// - infallible_destructuring_match: single-variant match on FFI result types
//   is intentional for clarity.
// - missing_safety_doc: FFI functions are documented in pulzz.h, not in
//   rustdoc safety sections.
#![allow(
    clippy::missing_safety_doc,
    clippy::not_unsafe_ptr_arg_deref,
    clippy::large_enum_variant,
    clippy::infallible_destructuring_match,
)]

pub mod client;
pub mod error;
pub mod server;
pub mod types;
pub mod version;

// Re-export all `extern "C"` functions + types at the crate root so they
// can be discovered via `use pulzz::*;` from tests.
pub use client::*;
pub use error::set_last_error;
pub use server::*;
pub use types::*;
pub use version::{ABI_VERSION, VERSION_STRING};

use std::os::raw::c_char;

/// ABI version (packed: major<<16 | minor<<8 | patch).
///
/// Returns `0x0004_0000` for v0.4.0.
#[unsafe(no_mangle)]
pub extern "C" fn pulzz_abi_version() -> u32 {
    version::ABI_VERSION
}

/// Human-readable version string. Caller must NOT free; the returned
/// pointer is valid for the lifetime of the shared library.
#[unsafe(no_mangle)]
pub extern "C" fn pulzz_version_string() -> *const c_char {
    static VERSION_CSTRING: std::sync::OnceLock<std::ffi::CString> = std::sync::OnceLock::new();
    let cstring = VERSION_CSTRING.get_or_init(|| {
        std::ffi::CString::new(version::VERSION_STRING).expect("version string has no NUL")
    });
    cstring.as_ptr()
}

/// Returns the last error message set on the current thread, or NULL if
/// no error is set. The returned pointer is valid until the next `pulzz_*`
/// call on the same thread.
#[unsafe(no_mangle)]
pub extern "C" fn pulzz_last_error() -> *const c_char {
    error::last_error_ptr()
}

/// Parse a raw wire-format Record from bytes. This is the wire-bytes
/// compatibility surface for cross-language tests (Go, C, Python).
///
/// # Arguments
/// - `bytes_ptr`: pointer to the raw wire bytes
/// - `bytes_len`: length of the raw wire bytes
/// - `out_item_id`: output parameter for the record's item_id (u64)
/// - `out_payload_ptr`: output parameter; will be set to a pointer to the
///   payload bytes (caller must NOT free; valid until the next pulzz_* call)
/// - `out_payload_len`: output parameter for the payload length
/// - `out_record_type`: output parameter for the record type (u8)
///
/// # Returns
/// `PulzzResult::Ok` on success, `PulzzResult::WireError` on parse failure.
///
/// # Safety
/// `bytes_ptr` must be valid for `bytes_len` bytes. The output pointers must
/// be valid for writing one u64, one *mut u8, one usize, one u8 respectively.
#[unsafe(no_mangle)]
pub extern "C" fn pulzz_parse_record(
    bytes_ptr: *const u8,
    bytes_len: usize,
    out_item_id: *mut u64,
    out_payload_ptr: *mut *mut u8,
    out_payload_len: *mut usize,
    out_record_type: *mut u8,
) -> types::PulzzResult {
    use std::panic::{catch_unwind, AssertUnwindSafe};
    let result = catch_unwind(AssertUnwindSafe(|| {
        if bytes_ptr.is_null() || out_item_id.is_null() || out_payload_ptr.is_null()
            || out_payload_len.is_null() || out_record_type.is_null()
        {
            return Err(types::PulzzResult::InvalidArg);
        }
        let bytes = unsafe { std::slice::from_raw_parts(bytes_ptr, bytes_len) };
        match shared_protocol::Record::from_bytes(bytes) {
            Ok(record) => {
                unsafe {
                    *out_item_id = record.header.item_id.0;
                    *out_payload_len = record.payload.len();
                    *out_record_type = record.header.record_type as u8;
                    // Store payload in thread-local buffer; pointer valid
                    // until the next pulzz_parse_record call on this thread.
                    *out_payload_ptr = error::store_payload_buffer(record.payload.clone());
                }
                Ok(types::PulzzResult::Ok)
            }
            Err(_) => Err(types::PulzzResult::InvalidArg),
        }
    }));
    match result {
        Ok(Ok(r)) => r,
        Ok(Err(r)) => r,
        Err(_) => types::PulzzResult::Internal,
    }
}
