//! pulzZ C ABI.
//!
//! Public surface: every `extern "C"` function is panic-safe (wrapped in
//! `catch_unwind`), null-checks every pointer, and reports failures via the
//! `pulzz_result_t` enum + thread-local last-error string.
//!
//! The crate is a `cdylib` producing `libpulzz.so` / `pulzz.dll` / a
//! static `.a`. The C header `pulzz.h` is generated by `cbindgen`.

#![allow(clippy::missing_safety_doc)]

pub mod client;
pub mod error;
pub mod server;
pub mod types;
pub mod version;

// Re-export all `extern "C"` functions + types at the crate root so they
// can be discovered via `use pulzz::*;` from tests.
pub use client::*;
pub use error::set_last_error;
pub use server::*;
pub use types::*;
pub use version::{ABI_VERSION, VERSION_STRING};

use std::os::raw::c_char;

/// ABI version (packed: major<<16 | minor<<8 | patch).
///
/// Returns `0x0004_0000` for v0.4.0.
#[unsafe(no_mangle)]
pub extern "C" fn pulzz_abi_version() -> u32 {
    version::ABI_VERSION
}

/// Human-readable version string. Caller must NOT free; the returned
/// pointer is valid for the lifetime of the shared library.
#[unsafe(no_mangle)]
pub extern "C" fn pulzz_version_string() -> *const c_char {
    static VERSION_CSTRING: std::sync::OnceLock<std::ffi::CString> = std::sync::OnceLock::new();
    let cstring = VERSION_CSTRING.get_or_init(|| {
        std::ffi::CString::new(version::VERSION_STRING).expect("version string has no NUL")
    });
    cstring.as_ptr()
}

/// Returns the last error message set on the current thread, or NULL if
/// no error is set. The returned pointer is valid until the next `pulzz_*`
/// call on the same thread.
#[unsafe(no_mangle)]
pub extern "C" fn pulzz_last_error() -> *const c_char {
    error::last_error_ptr()
}
