"""Python ↔ Rust cross-language wire-bytes compatibility test (Wave 5 T-5.b).

Verifies that Python can parse the same wire bytes that Rust produces.
The hex bytes below were generated by `cargo run --bin gen_cross_lang_bytes`
in sdk/src/bin/gen_cross_lang_bytes.rs. If the Rust wire format changes,
re-generate these bytes and update this test.

Run: pytest bindings/python/tests/test_cross_language.py -v
"""

import pulzz


# Record 1: ExactState, stream_id=1, item_id=42, payload=b"cross-lang-test"
# Generated by: cargo run --bin gen_cross_lang_bytes -p pulzz-sdk
BYTES_HEX_1 = (
    "020100000000000000000000000000000000000000"
    "110300002a000000000000000f000000"
    "63726f73732d6c616e672d74657374"
    "00000000000000000000000000000000"
)
EXPECTED_ITEM_ID_1 = 42
EXPECTED_PAYLOAD_1 = b"cross-lang-test"
EXPECTED_RECORD_TYPE_1 = 17  # ExactState

# Record 2: ExactState, stream_id=7, item_id=99, payload=b"hello", auth_tag=0xAB*16
BYTES_HEX_2 = (
    "020700000000000000000000000100000000000000"
    "11030000630000000000000005000000"
    "68656c6c6f"
    "abababababababababababababababab"
)
EXPECTED_ITEM_ID_2 = 99
EXPECTED_PAYLOAD_2 = b"hello"
EXPECTED_RECORD_TYPE_2 = 17  # ExactState


def test_parse_record_1_matches_rust():
    """Python parses Rust-generated bytes for record 1 (item_id=42)."""
    raw = bytes.fromhex(BYTES_HEX_1)
    item_id, payload, record_type = pulzz.parse_record(raw)
    assert item_id == EXPECTED_ITEM_ID_1, f"item_id: got {item_id}, want {EXPECTED_ITEM_ID_1}"
    assert bytes(payload) == EXPECTED_PAYLOAD_1, f"payload: got {payload!r}, want {EXPECTED_PAYLOAD_1!r}"
    assert record_type == EXPECTED_RECORD_TYPE_1, f"record_type: got {record_type}, want {EXPECTED_RECORD_TYPE_1}"


def test_parse_record_2_matches_rust():
    """Python parses Rust-generated bytes for record 2 (item_id=99)."""
    raw = bytes.fromhex(BYTES_HEX_2)
    item_id, payload, record_type = pulzz.parse_record(raw)
    assert item_id == EXPECTED_ITEM_ID_2, f"item_id: got {item_id}, want {EXPECTED_ITEM_ID_2}"
    assert bytes(payload) == EXPECTED_PAYLOAD_2, f"payload: got {payload!r}, want {EXPECTED_PAYLOAD_2!r}"
    assert record_type == EXPECTED_RECORD_TYPE_2, f"record_type: got {record_type}, want {EXPECTED_RECORD_TYPE_2}"


def test_wire_constants_match_rust():
    """Python verifies the same wire-protocol constants as Rust."""
    # BatchEnvelope = 21, ExactState = 17, AUTH_TAG_LEN = 16
    # These are verified in sdk/tests/wire_constants.rs
    assert pulzz.pulzz_version().startswith("pulzZ")


def test_round_trip_python_to_python():
    """Verify Python can parse bytes it generates (smoke test)."""
    # We can't generate bytes from Python (no to_bytes function), but we can
    # verify that parsing the known bytes twice gives the same result.
    raw1 = bytes.fromhex(BYTES_HEX_1)
    result1 = pulzz.parse_record(raw1)
    result1_again = pulzz.parse_record(raw1)
    assert result1 == result1_again
